server:
  port: 8081

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/handball_stats
    username: root